/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/protected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_protected"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/exchange-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange authorization code for tokens */
        post: operations["AuthController_exchangeCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh access token using refresh token */
        post: operations["AuthController_refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and invalidate refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Introspect token validity */
        post: operations["AuthController_introspect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List products with filtering and pagination */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** Create a new product */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advanced product search */
        get: operations["ProductsController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/sku/{sku}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by SKU */
        get: operations["ProductsController_findBySku"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/category/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get products by category */
        get: operations["ProductsController_findByCategory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product by ID */
        get: operations["ProductsController_findOne"];
        /** Update product */
        put: operations["ProductsController_update"];
        post?: never;
        /** Delete product */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product variants */
        get: operations["ProductsController_getVariants"];
        put?: never;
        /** Add variant to product */
        post: operations["ProductsController_addVariant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/variants/{variantId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update product variant */
        put: operations["ProductsController_updateVariant"];
        post?: never;
        /** Delete product variant */
        delete: operations["ProductsController_removeVariant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get product media */
        get: operations["ProductsController_getProductMedia"];
        put?: never;
        /** Attach media to product */
        post: operations["ProductsController_attachMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove media from product */
        delete: operations["ProductsController_detachMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/media/{mediaId}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set media as primary image */
        put: operations["ProductsController_updatePrimaryImage"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find all categories */
        get: operations["CategoriesController_findAll"];
        put?: never;
        /** Create a category */
        post: operations["CategoriesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find a category by ID */
        get: operations["CategoriesController_findOne"];
        put?: never;
        post?: never;
        /** Remove a category */
        delete: operations["CategoriesController_remove"];
        options?: never;
        head?: never;
        /** Update a category */
        patch: operations["CategoriesController_update"];
        trace?: never;
    };
    "/api/media/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_uploadFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/upload/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MediaController_uploadFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_getAllMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MediaController_getMediaById"];
        put: operations["MediaController_updateMedia"];
        post?: never;
        delete: operations["MediaController_deleteMedia"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FolderController_getFolders"];
        put?: never;
        post: operations["FolderController_createFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/folders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FolderController_getFolderById"];
        put: operations["FolderController_updateFolder"];
        post?: never;
        delete: operations["FolderController_deleteFolder"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/folders/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FolderController_getMediaInFolder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/folders/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FolderController_moveMediaToFolder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagController_getTags"];
        put?: never;
        post: operations["TagController_createTag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagController_getTagById"];
        put: operations["TagController_updateTag"];
        post?: never;
        delete: operations["TagController_deleteTag"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags/{id}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagController_getMediaWithTag"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags/media/{mediaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TagController_getTagsForMedia"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags/add-to-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TagController_addTagsToMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/tags/remove-from-media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TagController_removeTagsFromMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /**
             * @description Username for the account
             * @example johndoe
             */
            username: string;
            /**
             * @description Email address
             * @example john.doe@example.com
             */
            email: string;
            /**
             * @description Password for the account
             * @example password123
             */
            password: string;
            /**
             * @description First name
             * @example John
             */
            firstName?: string;
            /**
             * @description Last name
             * @example Doe
             */
            lastName?: string;
        };
        TokenResponse: {
            /**
             * @description Access token for API authentication
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /**
             * @description Refresh token to get a new access token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
            /**
             * @description Token expiration time in seconds
             * @example 3600
             */
            expiresIn: number;
            /**
             * @description ID token containing user information
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            idToken?: string;
        };
        LoginDto: {
            /**
             * @description User password
             * @example password123
             */
            password: string;
            /**
             * @description Username for the account
             * @example johndoe
             */
            username: string;
        };
        CodeExchangeDto: {
            /**
             * @description Authorization code from OAuth provider
             * @example abcdef123456
             */
            code: string;
            /**
             * @description Code verifier used in PKCE flow
             * @example randomstring123456
             */
            codeVerifier: string;
        };
        TokenDto: {
            /**
             * @description Refresh token
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        LogoutDto: {
            /**
             * @description Refresh token to invalidate
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            refreshToken: string;
        };
        CreateProductDto: {
            /**
             * @description Product SKU (Stock Keeping Unit) - must be unique
             * @example LAPTOP-001
             */
            sku: string;
            /**
             * @description Product name
             * @example MacBook Pro 16-inch
             */
            name: string;
            /**
             * @description Product description
             * @example High-performance laptop with M2 chip and 16GB RAM
             */
            description?: string;
            /**
             * @description Product price (must be positive)
             * @example 2499.99
             */
            price: string;
            /**
             * @description Product currency
             * @default USD
             * @example USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
            /**
             * @description Product active status
             * @default true
             * @example true
             */
            isActive: boolean;
            /**
             * @description Array of category IDs to assign to this product
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            categoryIds?: string[];
            /** @description Initial product variants to create */
            variants?: {
                /** @example Color */
                name?: string;
                /** @example Space Gray */
                value?: string;
            }[];
            /**
             * @description Array of image IDs to assign to this product
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            imageIds?: string[];
        };
        CategoryDto: {
            /**
             * @description Category ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Category name
             * @example Electronics
             */
            name: string;
            /**
             * @description Category slug
             * @example electronics
             */
            slug: string;
            /**
             * @description Parent category ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            parentId: string;
            /**
             * Format: date-time
             * @description Category created at
             * @example 2021-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Category updated at
             * @example 2021-01-01T00:00:00.000Z
             */
            updatedAt: string;
            /** @description Category children */
            children: components["schemas"]["CategoryDto"][];
        };
        ProductVariantDto: {
            /**
             * @description Variant ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Product ID this variant belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            productId: string;
            /**
             * @description Variant name (e.g., Color, Size, Material)
             * @example Color
             */
            name: string;
            /**
             * @description Variant value (e.g., Red, Large, Cotton)
             * @example Red
             */
            value: string;
        };
        ProductMediaDto: {
            /**
             * @description Product media ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Product ID this media belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            productId: string;
            /**
             * @description Media URL
             * @example https://example.com/images/product-123.jpg
             */
            url: string;
            /**
             * @description Media ID from media service
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            mediaId: string;
            /**
             * @description Original filename
             * @example product-image.jpg
             */
            originalFilename: string;
            /**
             * @description MIME type
             * @example image/jpeg
             */
            mimeType: string;
            /**
             * @description File size in bytes
             * @example 1024000
             */
            size: number;
            /**
             * @description Media type
             * @example IMAGE
             */
            type: string;
            /**
             * @description Image width in pixels
             * @example 1920
             */
            width?: number;
            /**
             * @description Image height in pixels
             * @example 1080
             */
            height?: number;
        };
        ProductDto: {
            /**
             * @description Product ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Product SKU (Stock Keeping Unit)
             * @example LAPTOP-001
             */
            sku: string;
            /**
             * @description Product name
             * @example MacBook Pro 16-inch
             */
            name: string;
            /**
             * @description Product description
             * @example High-performance laptop with M2 chip
             */
            description?: string;
            /**
             * @description Product price
             * @example 2499.99
             */
            price: string;
            /**
             * @description Product currency
             * @example USD
             * @enum {string}
             */
            currency: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
            /**
             * @description Product active status
             * @example true
             */
            isActive: boolean;
            /**
             * Format: date-time
             * @description Product creation date
             * @example 2024-01-15T10:30:00Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Product last update date
             * @example 2024-01-15T10:30:00Z
             */
            updatedAt: string;
            /** @description Product categories */
            categories?: components["schemas"]["CategoryDto"][];
            /** @description Product variants */
            variants?: components["schemas"]["ProductVariantDto"][];
            /** @description Product media/images */
            images?: components["schemas"]["ProductMediaDto"][];
        };
        QueryProductResponse: {
            /** @description Array of products */
            items?: components["schemas"]["ProductDto"][];
            /** @description Pagination metadata */
            meta?: {
                /** @example 1 */
                page?: number;
                /** @example 20 */
                limit?: number;
                /** @example 150 */
                total?: number;
                /** @example 8 */
                totalPages?: number;
            };
        };
        UpdateProductDto: {
            /**
             * @description Product SKU (Stock Keeping Unit) - must be unique
             * @example LAPTOP-001-V2
             */
            sku?: string;
            /**
             * @description Product name
             * @example MacBook Pro 16-inch (Updated)
             */
            name?: string;
            /**
             * @description Product description
             * @example High-performance laptop with M2 Pro chip and 32GB RAM
             */
            description?: string;
            /**
             * @description Product price (must be positive)
             * @example 2999.99
             */
            price?: string;
            /**
             * @description Product currency
             * @example EUR
             * @enum {string}
             */
            currency?: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
            /**
             * @description Product active status
             * @example false
             */
            isActive?: boolean;
            /**
             * @description Array of category IDs to assign to this product (replaces existing categories)
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000",
             *       "987fcdeb-51a2-43d1-b789-fedcba098765"
             *     ]
             */
            categoryIds?: string[];
            /**
             * @description Array of image IDs to assign to this product
             * @example [
             *       "123e4567-e89b-12d3-a456-426614174000"
             *     ]
             */
            imageIds?: string[];
        };
        CreateProductVariantDto: {
            /**
             * @description Variant name (e.g., Color, Size, Material)
             * @example Color
             */
            name: string;
            /**
             * @description Variant value (e.g., Red, Large, Cotton)
             * @example Space Gray
             */
            value: string;
        };
        ProductVariantResponseDto: {
            /**
             * @description Variant ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Product ID this variant belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            productId: string;
            /**
             * @description Variant name
             * @example Color
             */
            name: string;
            /**
             * @description Variant value
             * @example Space Gray
             */
            value: string;
        };
        UpdateProductVariantDto: {
            /**
             * @description Variant name (e.g., Color, Size, Material)
             * @example Color
             */
            name?: string;
            /**
             * @description Variant value (e.g., Red, Large, Cotton)
             * @example Silver
             */
            value?: string;
        };
        AttachMediaToProductDto: {
            /**
             * @description Media ID from media service to attach to product
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            mediaId: string;
            /**
             * @description Set this media as the primary product image
             * @default false
             * @example true
             */
            isPrimary: boolean;
            /**
             * @description Alternative text for accessibility
             * @example MacBook Pro 16-inch in Space Gray
             */
            altText?: string;
        };
        ProductMediaResponseDto: {
            /**
             * @description Product media ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id: string;
            /**
             * @description Product ID this media belongs to
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            productId: string;
            /**
             * @description Media URL
             * @example https://example.com/images/product-123.jpg
             */
            url: string;
            /**
             * @description Media ID from media service
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            mediaId: string;
            /**
             * @description Original filename
             * @example product-image.jpg
             */
            originalFilename: string;
            /**
             * @description MIME type
             * @example image/jpeg
             */
            mimeType: string;
            /**
             * @description File size in bytes
             * @example 1024000
             */
            size: number;
            /**
             * @description Media type
             * @example IMAGE
             */
            type: string;
            /**
             * @description Image width in pixels
             * @example 1920
             */
            width?: number;
            /**
             * @description Image height in pixels
             * @example 1080
             */
            height?: number;
        };
        DetachMediaFromProductResponseDto: {
            /**
             * @description Product ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            productId: string;
            /**
             * @description Detached media ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            mediaId: string;
            /**
             * @description Operation success status
             * @example true
             */
            success: boolean;
        };
        CreateCategoryDto: {
            /**
             * @description Category name
             * @example Electronics
             */
            name: string;
            /**
             * @description Category slug
             * @example electronics
             */
            slug: string;
            /**
             * @description Parent category ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            parentId: string;
        };
        PaginationMeta: {
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Number of items per page
             * @example 10
             */
            limit: number;
            /**
             * @description Total number of items
             * @example 100
             */
            totalCount: number;
            /**
             * @description Total number of pages
             * @example 10
             */
            totalPages: number;
        };
        QueryCategoryResponse: {
            /** @description List of items */
            data: components["schemas"]["CategoryDto"][];
            /** @description Pagination metadata */
            meta: components["schemas"]["PaginationMeta"];
        };
        UpdateCategoryDto: {
            /**
             * @description Category name
             * @example Electronics
             */
            name: string;
            /**
             * @description Category slug
             * @example electronics
             */
            slug: string;
            /**
             * @description Parent category ID
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            parentId: string;
        };
        FileUploadDto: {
            /**
             * Format: binary
             * @description Media file to upload
             */
            file: string;
            /** @description Whether the file is publicly accessible */
            isPublic?: boolean;
            /** @description Path where the file should be stored */
            path?: string;
            /** @description Additional metadata for the file */
            metadata?: {
                [key: string]: unknown;
            };
        };
        BatchFileUploadDto: {
            /** @description Media files to upload */
            files: string[];
            /** @description Whether the files are publicly accessible */
            isPublic?: boolean;
            /** @description Path where the files should be stored */
            path?: string;
            /** @description Additional metadata for the files */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        MediaType: "IMAGE" | "VIDEO" | "AUDIO" | "DOCUMENT";
        /**
         * @description Status of the media processing
         * @enum {string}
         */
        MediaStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /**
         * @description Storage provider for the media
         * @enum {string}
         */
        StorageProvider: "LOCAL" | "S3" | "CLOUDINARY" | "AZURE";
        UpdateMediaDto: {
            /** @description Whether the media is publicly accessible */
            isPublic?: boolean;
            /** @description Additional metadata for the media */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Path where the media is stored */
            path?: string;
            /** @description Original filename of the media */
            originalFilename?: string;
            /** @description MIME type of the media file */
            mimeType?: string;
            /** @description Media type category */
            type?: components["schemas"]["MediaType"];
            /** @description Status of the media processing */
            status?: components["schemas"]["MediaStatus"];
            /** @description Storage provider for the media */
            provider?: components["schemas"]["StorageProvider"];
            /** @description URL to access the media */
            url?: string;
        };
        CreateFolderDto: {
            /** @description Name of the folder */
            name: string;
            /** @description ID of the parent folder */
            parentId?: string;
            /** @description ID of the folder owner */
            ownerId: string;
        };
        UpdateFolderDto: {
            /** @description New name for the folder */
            name?: string;
            /** @description New parent folder ID (null for root folder) */
            parentId?: string | null;
        };
        MoveMediaToFolderDto: {
            /** @description List of media IDs to move */
            mediaIds: string[];
            /** @description Target folder ID */
            folderId: string;
        };
        CreateTagDto: {
            /** @description Tag name */
            name: string;
            /** @description Tag description */
            description?: string;
        };
        UpdateTagDto: {
            /** @description New tag name */
            name?: string;
            /** @description New tag description */
            description?: string;
        };
        AddTagsToMediaDto: {
            /** @description List of media IDs to tag */
            mediaIds: string[];
            /** @description List of tag IDs to apply */
            tagIds: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppController_protected: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid input data */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description User successfully logged in */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_exchangeCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CodeExchangeDto"];
            };
        };
        responses: {
            /** @description Authorization code exchanged successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Failed to exchange code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenDto"];
            };
        };
        responses: {
            /** @description Token successfully refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid or expired refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutDto"];
            };
        };
        responses: {
            /** @description Successfully logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_introspect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token introspection result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query?: {
                /** @description Search term for product name or description */
                search?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Sort by */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                sortOrder?: "asc" | "desc";
                /** @description Include total count */
                includeTotalCount?: boolean;
                /** @description Filter by category ID */
                categoryId?: string;
                /** @description Filter by multiple category IDs */
                categoryIds?: string[];
                /** @description Filter by currency */
                currency?: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
                /** @description Minimum price filter */
                minPrice?: number;
                /** @description Maximum price filter */
                maxPrice?: number;
                /** @description Filter by active status */
                isActive?: boolean;
                /** @description Field to sort by */
                sortField?: "name" | "price" | "sku" | "createdAt" | "updatedAt";
                /** @description Include product variants in response */
                includeVariants?: boolean;
                /** @description Include product media/images in response */
                includeMedia?: boolean;
                /** @description Include product categories in response */
                includeCategories?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProductResponse"];
                };
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Product created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductsController_search: {
        parameters: {
            query: {
                /** @description Search term */
                q: string;
                /** @description Search term for product name or description */
                search?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Sort by */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                sortOrder?: "asc" | "desc";
                /** @description Include total count */
                includeTotalCount?: boolean;
                /** @description Filter by category ID */
                categoryId?: string;
                /** @description Filter by multiple category IDs */
                categoryIds?: string[];
                /** @description Filter by currency */
                currency?: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
                /** @description Minimum price filter */
                minPrice?: number;
                /** @description Maximum price filter */
                maxPrice?: number;
                /** @description Filter by active status */
                isActive?: boolean;
                /** @description Field to sort by */
                sortField?: "name" | "price" | "sku" | "createdAt" | "updatedAt";
                /** @description Include product variants in response */
                includeVariants?: boolean;
                /** @description Include product media/images in response */
                includeMedia?: boolean;
                /** @description Include product categories in response */
                includeCategories?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProductResponse"];
                };
            };
        };
    };
    ProductsController_findBySku: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product SKU */
                sku: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductsController_findByCategory: {
        parameters: {
            query?: {
                /** @description Search term for product name or description */
                search?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Sort by */
                sortBy?: string;
                /** @description Sort order (asc or desc) */
                sortOrder?: "asc" | "desc";
                /** @description Include total count */
                includeTotalCount?: boolean;
                /** @description Filter by multiple category IDs */
                categoryIds?: string[];
                /** @description Filter by currency */
                currency?: "USD" | "EUR" | "GBP" | "JPY" | "CAD" | "AUD";
                /** @description Minimum price filter */
                minPrice?: number;
                /** @description Maximum price filter */
                maxPrice?: number;
                /** @description Filter by active status */
                isActive?: boolean;
                /** @description Field to sort by */
                sortField?: "name" | "price" | "sku" | "createdAt" | "updatedAt";
                /** @description Include product variants in response */
                includeVariants?: boolean;
                /** @description Include product media/images in response */
                includeMedia?: boolean;
                /** @description Include product categories in response */
                includeCategories?: boolean;
            };
            header?: never;
            path: {
                /** @description Category ID */
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Products in category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryProductResponse"];
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Product updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    ProductsController_getVariants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product variants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariantResponseDto"][];
                };
            };
        };
    };
    ProductsController_addVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductVariantDto"];
            };
        };
        responses: {
            /** @description Variant added successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariantResponseDto"];
                };
            };
        };
    };
    ProductsController_updateVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
                /** @description Variant ID */
                variantId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductVariantDto"];
            };
        };
        responses: {
            /** @description Variant updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductVariantResponseDto"];
                };
            };
        };
    };
    ProductsController_removeVariant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
                /** @description Variant ID */
                variantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Variant deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProductsController_getProductMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product media */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMediaResponseDto"][];
                };
            };
        };
    };
    ProductsController_attachMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttachMediaToProductDto"];
            };
        };
        responses: {
            /** @description Media attached successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductMediaResponseDto"];
                };
            };
        };
    };
    ProductsController_detachMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
                /** @description Media ID */
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Media removed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetachMediaFromProductResponseDto"];
                };
            };
        };
    };
    ProductsController_updatePrimaryImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product ID */
                id: string;
                /** @description Media ID */
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Primary image updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDto"];
                };
            };
        };
    };
    CategoriesController_findAll: {
        parameters: {
            query?: {
                /** @description Search query */
                search?: string;
                /** @description Page number */
                page?: number;
                /** @description Limit number */
                limit?: number;
                /** @description Sort by */
                sortBy?: string;
                /** @description Sort order */
                sortOrder?: string;
                /** @description Include total count */
                includeTotalCount?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryCategoryResponse"];
                };
            };
        };
    };
    CategoriesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    CategoriesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    CategoriesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    CategoriesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDto"];
                };
            };
        };
    };
    MediaController_uploadFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_uploadFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchFileUploadDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_getAllMedia: {
        parameters: {
            query?: {
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter by media type */
                type?: components["schemas"]["MediaType"];
                /** @description Search by filename */
                search?: string;
                /** @description Filter by tags */
                tags?: string[];
                /** @description Filter by folder ID */
                folderId?: string;
                /** @description Filter by owner ID */
                ownerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_getMediaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_updateMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMediaDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MediaController_deleteMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_getFolders: {
        parameters: {
            query?: {
                /** @description ID of the parent folder */
                parentId?: string;
                /** @description Search folders by name */
                search?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description ID of the folder owner */
                ownerId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_createFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFolderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_getFolderById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_updateFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFolderDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_deleteFolder: {
        parameters: {
            query: {
                deleteContents: boolean;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_getMediaInFolder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FolderController_moveMediaToFolder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveMediaToFolderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_getTags: {
        parameters: {
            query?: {
                /** @description Search tags by name */
                search?: string;
                /** @description Page number (1-based) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_createTag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTagDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_getTagById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_updateTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTagDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_deleteTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_getMediaWithTag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_getTagsForMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mediaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_addTagsToMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagsToMediaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TagController_removeTagsFromMedia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddTagsToMediaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
